blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/kibouakari/S-PDF/discussions
    about: Have a question instead of a bug/feature request? Start a discussion.
